FROM alpine:latest

RUN apk update \
    && apk add --no-cache bash mosquitto \
    && rm -fr /tmp/*

COPY mqtt.sh /
COPY mosquitto.conf /
WORKDIR /
RUN touch /etc/mosquitto/passwd
RUN mkdir -p /etc/mosquitto/conf.d \
    && chmod -R o+w /etc/mosquitto/conf.d/
RUN mkdir -p /var/log/mosquitto \
    && chmod -R o+w /var/log/mosquitto/
CMD ["./mqtt.sh"]
